version: '3.1'

services:
  db2:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: WST_ITPL_server
    ports: 
      - "3305:3306"
    volumes:
      - ./data:/var/lib/mysql

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/my_app_dir
    ports:
      - "8000:8000"
    depends_on:
      - db2