# Generated by Django 4.0.1 on 2022-01-26 09:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=200)),
                ('delay', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('url', models.CharField(default='???', max_length=45, unique=True)),
                ('roomNr', models.CharField(default='???', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StationHasConfigurationJT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('configurationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.configuration')),
                ('stationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.station')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('createdAt', models.DateTimeField()),
                ('station_jt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.stationhasconfigurationjt')),
            ],
        ),
    ]
