# Generated by Django 3.2.8 on 2021-10-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_auto_20211013_1334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Configurations',
            new_name='Configuration',
        ),
        migrations.RenameModel(
            old_name='Logs',
            new_name='Log',
        ),
        migrations.RenameModel(
            old_name='Stations',
            new_name='Station',
        ),
    ]
