# Generated by Django 4.0.1 on 2022-02-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_alter_station_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='roomNr',
            field=models.CharField(default='???', max_length=10),
        ),
    ]
