# Generated by Django 3.2.8 on 2021-10-13 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_auto_20211013_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationHasConfigurationJT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configurationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.configuration')),
                ('stationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.station')),
            ],
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
