# Generated by Django 3.2.8 on 2021-10-20 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_auto_20211013_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationhasconfigurationjt',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('createdAt', models.DateTimeField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.stationhasconfigurationjt')),
            ],
        ),
    ]
